--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HungerWars951/ReactionPM
build-by-default: true
branches:
- main
projects:
  ReactionPM:
    path: ""
    lint: false
    icon: "icon.png"
...
